name: Deploy infra

on: workflow_dispatch

env:
  StorageNamePrefix: wonsoonge
  resourceGroupName: rg-wonsoong

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

    # Login into Azure
      - name: Azure Login
        uses: Azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


    # Deploy Bicep template
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ../../infra/templates/deploy_envt.bicep
          parameters: ../../infra/templates/deploy_envt.parameters.json storageNamePrefix=${{ env.StorageNamePrefix }}